- hosts: localhost
  pre_tasks:
  - name: update pacman 
    become: true
    community.general.pacman:
      force: true
      update_cache: true
      state: present

  tasks:
    - name: core
      include_tasks:
        file: tasks/core.yml
        apply:
          tags:
            - core
            - always
      tags: always

    - name: zsh
      include_tasks:
        file: tasks/zsh.yml
        apply:
          tags:
            - zsh
      tags: always

    - name: dotfiles
      include_tasks:
        file: tasks/dotfiles.yml
        apply:
          tags:
            - dotfiles
      tags: always

    - name: neovim 
      include_tasks:
        file: tasks/neovim.yml
        apply:
          tags:
            - neovim
      tags: always

    - name: node
      include_tasks:
        file: tasks/node.yml
        apply:
          tags:
            - node
      tags: always

    - name: docker
      include_tasks:
        file: tasks/docker.yml
        apply:
          tags:
            - docker
      tags: always

    - name: chrome
      include_tasks:
        file: tasks/chrome.yml
        apply:
          tags:
            - chrome
      tags: always

    - name: productivity
      include_tasks:
        file: tasks/productivity.yml
        apply:
          tags:
            - productivity
      tags: always

    - name: spotify 
      include_tasks:
        file: tasks/spotify.yml
        apply:
          tags:
            - productivity
      tags: always

