- name: install stow
  package:
    name: stow
    state: latest

- name: clone dotfiles repo
  become: true
  become_user: radoslawgrochowski
  ansible.builtin.git:
    repo: https://github.com/radoslawgrochowski/dotfiles.git
    dest: ~/Projects/dotfiles

- name: make dotfiles
  become: true
  become_user: radoslawgrochowski
  make:
    chdir: ~/Projects/dotfiles
