- name: check jira-cli bin
  stat:
    path: /usr/local/bin/jira
  register: jira_cli 

- name: unarchive jira-cli 
  unarchive:
    src: https://github.com/ankitpokhrel/jira-cli/releases/download/v1.0.0-beta/jira_1.0.0-beta_linux_x86_64.tar.gz
    dest: /tmp
    remote_src: yes
  when: not jira_cli.stat.exists

- name: copy jira bin
  ansible.builtin.copy:
    src: /tmp/jira_1.0.0-beta_linux_x86_64/bin/
    dest: /usr/local/bin/
    mode: '0755'
  when: not jira_cli.stat.exists
