- name: add neovim repository
  apt_repository:
    repo: ppa:neovim-ppa/unstable

- name: install neovim
  package:
    name:
      - neovim
    state: latest

- name: clone packer repo
  become: true
  become_user: radoslawgrochowski
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim

- name: check lua-language-server 
  stat:
    path: /usr/local/bin/lua-language-server
  register: lua_language_server 

- name: create temp directory for lua-language-server 
  ansible.builtin.file:
    path: /usr/local/lua-language-server
    state: directory
    mode: '0755'
  when: not lua_language_server.stat.exists

- name: unarchive lua-language-server
  unarchive: 
    src: https://github.com/sumneko/lua-language-server/releases/download/3.2.2/lua-language-server-3.2.2-linux-x64.tar.gz
    dest: /usr/local/lua-language-server
    remote_src: yes
  when: not lua_language_server.stat.exists

- name: Creating a file with content
  copy:
    dest: /usr/local/bin/lua-language-server
    content: |
      #!/bin/bash
      exec "/usr/local/lua-language-server/bin/lua-language-server" "$@"
    mode: '0755'
  when: not lua_language_server.stat.exists

