- name: add shutter repository
  apt_repository:
    repo: ppa:shutter/ppa

- name: add google-drive-ocamlfuse repository
  apt_repository:
    repo: ppa:alessandro-strada/ppa

- name: install various productivity tools
  package:
    name:
      - ffmpeg
      - keepassxc
      - ripgrep
      - feh
      - neofetch
      - picom
      - shutter
      - pavucontrol
      - fd-find
      - xcwd
      - google-drive-ocamlfuse
    state: latest

